# SITE CONFIGURATION
title: Nilson Cunha # your site title
author: nilsoncunha # You :P
description: # Meta description of Homepage
  Neste portfólio terá minhas análises e estudos referente a Data Science, Machine Learning,
  banco de dados NoSQL, entre outros.
baseurl: "/portfolioweb" # the subpath of your site, e.g. /blog
url: "https://nilsoncunha.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Nilson Cunha
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/nilsoncunhan
    #- https://plus.google.com/+BenBalter
    - https://github.com/nilsoncunha
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Início', link: '/'}
  - {name: 'Sobre', link: '/about'}
  - {name: 'Contato', link: '/contact'}

tagline:
  Aqui você encontrará assuntos referente a Data Science, Machine Learning e mais...

hero_img: posts/home_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: nilson.cunhan@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  nilsoncunha # replace with your_github_username or comment to remove link from footer
#instagram_username: nilsoncunhan # replace with your_instagram_username or comment to remove link from footer
linkedin_username: nilsoncunhan # replace with your_instagram_username or comment to remove link from footer

disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
